# -*- coding: utf-8 -*-
"""task8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GAl0ztsRASADW4HLGV1O_qBLy_Dmb1t
"""

class SalaryNotInRangeError(Exception):
  """Exception raised for errors in the input salary.

  Attributes:
   salary -- input salary which caused the error
   message -- explanation of the error"""

  def __init__(self, salary, message="Salary is not in (5000, 15000) range"):
   self.salary = salary
   self.message = message
   super().__init__(self.message)

# Start of Program
salary = int(input("Enter salary amount: "))
if not 5000 < salary < 15000:
  logging.error("Error!")
  raise SalaryNotInRangeError(salary)