# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XikClTMTNaGH9gHLO6S3eFNgl1vQVx5W

TASK-2
"""

import logging

logging.basicConfig(format='%(process)d-%(levelname)s-%(message)s')
logging.warning('This is a Warning')

# Commented out IPython magic to ensure Python compatibility.
# %%python
# import logging
# 
# logging.basicConfig(format='%(asctime)s - %(message)s',
# level=logging.INFO)
# logging.info('Admin logged in')

# Commented out IPython magic to ensure Python compatibility.
# %%python
# import logging
# 
# logging.basicConfig(format='%(asctime)s - %(message)s',
# datefmt='%d-%b-%y %H:%M:%S')
# logging.warning('Admin logged out')