# -*- coding: utf-8 -*-
"""task5_yml

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GAl0ztsRASADW4HLGV1O_qBLy_Dmb1t
"""

# Commented out IPython magic to ensure Python compatibility.
# %%python
# 
# import logging
# import logging.config
# import yaml
# 
# with open('task5.yml', 'r') as f:
#   config = yaml.safe_load(f.read())
#   logging.config.dictConfig(config)
# 
# logger = logging.getLogger(__name__)
# 
# logger.debug('This is a debug message')