# -*- coding: utf-8 -*-
"""Task5_conf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-egmzBfx8DhILha9frqCPEAVom9ogPP

Task5
"""

import logging
import logging.config

logging.config.fileConfig(fname='task5.conf', disable_existing_loggers=False)

# Get the logger specified in the file
logger = logging.getLogger(__name__)

logger.debug('This is a debug message')