# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XikClTMTNaGH9gHLO6S3eFNgl1vQVx5W

TASK-1
"""

import logging

logging.basicConfig(filename='app.log',
filemode='w',
format='%(name)s - %(levelname)s - %(message)s')
logging.warning('This will get logged to a file')

