# -*- coding: utf-8 -*-
"""Task 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XikClTMTNaGH9gHLO6S3eFNgl1vQVx5W

TASK-0
"""

import logging

logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

